services:
    _defaults:
        public: false

    yamilovs_sms.prototype.provider.sms_ru:
        class: Yamilovs\Bundle\SmsBundle\Provider\SmsRuProvider

    yamilovs_sms.prototype.provider.sms_aero:
        class: Yamilovs\Bundle\SmsBundle\Provider\SmsAeroProvider

    yamilovs_sms.prototype.provider.sms_discount:
        class: Yamilovs\Bundle\SmsBundle\Provider\SmsDiscountProvider

    yamilovs_sms.prototype.provider.sms_center:
        class: Yamilovs\Bundle\SmsBundle\Provider\SmsCenterProvider

    yamilovs_sms.provider.manager:
        class: Yamilovs\Bundle\SmsBundle\Service\ProviderManager

    Yamilovs\Bundle\SmsBundle\Service\ProviderManager: '@yamilovs_sms.provider.manager'

    yamilovs_sms.command.test_delivery:
        class: Yamilovs\Bundle\SmsBundle\Command\TestDeliveryCommand
        arguments: ['@yamilovs_sms.provider.manager']
        tags:
            - { name: 'console.command' }